# Generated by Django 5.1.2 on 2025-05-11 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HydrologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_average_january', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_february', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_march', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_april', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_may', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_june', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_july', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_august', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_september', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_october', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_november', models.DecimalField(decimal_places=4, max_digits=10)),
                ('temperature_average_december', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_january', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_february', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_march', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_april', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_may', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_june', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_july', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_august', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_september', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_october', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_november', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precipitation_average_december', models.DecimalField(decimal_places=4, max_digits=10)),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
    ]
